# Generated by Django 6.0.1 on 2026-01-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='educenters',
            options={'verbose_name': 'Educenter', 'verbose_name_plural': 'Educenters'},
        ),
        migrations.RemoveField(
            model_name='educenters',
            name='courses',
        ),
        migrations.AddField(
            model_name='educenters',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='learning_centers.courses'),
        ),
    ]
