# Generated by Django 6.0.1 on 2026-01-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_centers', '0002_alter_courses_options_alter_educenters_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educenters',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='educenters',
            name='phone_number_extra',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
