# Generated by Django 6.0.1 on 2026-01-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_centers', '0003_educenters_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educenters',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='educenters', to='learning_centers.courses'),
        ),
    ]
