# Generated by Django 6.0.1 on 2026-01-25 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_centers', '0004_alter_educenters_courses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies', to='learning_centers.educenters')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies', to='learning_centers.courses')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
