# Generated by Django 6.0.1 on 2026-01-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_centers', '0005_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Application', 'verbose_name_plural': 'Applications'},
        ),
        migrations.AddField(
            model_name='application',
            name='index',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
