# Generated by Django 6.0.1 on 2026-01-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_centers', '0008_alter_application_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='index',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
