# Generated by Django 6.0.1 on 2026-01-27 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_centers', '0009_alter_application_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educenters',
            old_name='bio',
            new_name='info',
        ),
    ]
