# Generated by Django 6.0.1 on 2026-01-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_centers', '0010_rename_bio_educenters_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='educenters',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educenters',
            name='official_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educenters',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='educenter_images/'),
        ),
    ]
