# Generated by Django 5.2.11 on 2026-02-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_centers', '0013_educenters_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='educenters',
            name='have_right_to_add',
            field=models.BooleanField(default=False),
        ),
    ]
