# Generated by Django 5.2.11 on 2026-02-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_centers', '0014_educenters_have_right_to_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educenters',
            name='have_right_to_add',
        ),
    ]
