# Generated by Django 6.0.1 on 2026-01-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_control', '0002_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
