# Generated by Django 6.0.1 on 2026-01-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_control', '0003_delete_application'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
