# Generated by Django 5.2.11 on 2026-02-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_control', '0007_roles_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
    ]
