# Generated by Django 5.2.11 on 2026-02-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_control', '0008_alter_roles_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='have_right_to_add',
            field=models.BooleanField(default=False),
        ),
    ]
